# Generated by Django 3.1.4 on 2020-12-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iccard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('id_card', models.CharField(max_length=45)),
                ('cardnum', models.CharField(max_length=45)),
                ('birthday', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=45)),
                ('carddate', models.CharField(max_length=45)),
                ('temperature', models.CharField(max_length=45)),
                ('weight', models.CharField(max_length=45)),
                ('pressures', models.CharField(db_column='pressureS', max_length=45)),
                ('pressured', models.CharField(db_column='pressureD', max_length=45)),
                ('testdate', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'iccard',
                'managed': False,
            },
        ),
    ]
